version: '3'
services:
  go_graphql_sample_db:
    build: db/go_graphql_sample
    container_name: go_graphql_sample_db
    ports:
      - 3306:3306
    volumes:
      - mysql-go-graphql-sample-app-data:/var/lib/mysql
      - ./db/go_graphql_sample/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_APP_USER: sample
      MYSQL_APP_USER_PASSWORD: sample
      MYSQL_DATABASE: sample 
    restart: unless-stopped

volumes:
  mysql-go-graphql-sample-app-data:
    driver: local
